# Disable sudo to speed up the build

sudo: false



# Set the build language to Python

language: python

#For Gh-pages
branches:
  only:
    - master

#setting environment variables

env:
  -global:
    -github_token: asdasd

# Set the python version to 2.7

python: 2.7



# Install the codecov pip dependency

install:

  - pip install codecov



# Run the unit test

script:

  - coverage run test.py



# Push the results back to codecov

after_success:

  - codecov
