# Disable sudo to speed up the build

sudo: false



# Set the build language to Python

language: python

#For Gh-pages
branches:
  only:
    - master

#setting environment variables

env:
  -global:
    -github_token: asdasd
    secure: "uu6DCMhxxGC/PgoUpJ/5BFft8WaY0edYkkf5FDl+JknnJc3ntnzcXGoisMnS2DfE/Kn2DpAyaLORIEjG7SP+KVg6z7d8E3S7BXJM6H+A1wc7bJeSb6Yu1SpsIYv+V9vjekjwjFbNt0OzOINsVnOwbyESfYhYo/QBxRXPDgO6wT06M+zuQ1gWjzTVjTIjGVJ+n0Y0929g7r2+ZPa+D+5v0LdoEiAjkJlHzEf+z4MOi5DVuv9yzVhImVmP+xEdGImuGGFGiD83ja7jVT7nzqc2LU6RSsZf4C4UwdUeCoR93u0QjH2TeAOg196cTQ5sZRunbMvQdoPaUUHlz2RxVVSe49AdDGv+b1wai2mFkLg2W5/Qg0k4yHKjfUWCgmQ4T1yNL60RSzWqDU1U34hOcGTqhuNTNuBJvUQV3S2TICZXhanbrMCr/mlFYHSC5U7SQ/j4E93o7SEIx3FCR4J0YYVBzgo0RsJa1xBQ+JORs04WsYum2gLa6XVpa0A66vbj6ZPQ4f9BshI7EtJOPsUNebawXJtE3KS0egCNPIL7QECdMTjmVwaUFlhiBU7+yXLT5x4ZCObGOQv8GJr2D+MI95eS9xwBgr2xUfTi3dwnMV55ETqvaa1ZXWNsXE15ItEvJFI2HAexJoemnHm+EkFNRcAuY6CD7eD8OrYwtoWTON1nDhA="

# Set the python version to 2.7

python: 2.7



# Install the codecov pip dependency

install:

  - pip install codecov



# Run the unit test

script:

  - coverage run test.py



# Push the results back to codecov

after_success:

  - codecov
